debug: false #디버그 로그 보기
management.endpoints.web.exposure.include: "*" #액추에이터 엔드포인트 감춰진거 모두 활성화

logging:
  level:
    org.springframwork.web.servlet: debug # debug: request, response만 뽑아 봄
    org.hibernate.type.descriptor.sql.BasicBinder: trace #jpa

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: bonoo
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true #더미데이터 쿼리
    hibernate.ddl-auto: create #테스트 실행시 자동으로 ddl 작성해줌
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
#  h2.console.enabled: true #h2 console 사용여부?
  sql.init.mode: always

  data.rest:
    base-path: /api
    detection-strategy: annotated

